import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiTypescript,
  SiAngular,
  SiReact,
  SiHtml5,
  SiCss3,
  SiSass,
  SiJquery,
  SiTailwindcss,
  SiBootstrap,
  SiSpringboot,
  SiLaravel,
  SiPhp,
  SiMysql,
  SiMongodb,
  SiPostgresql,
  SiJira,
  SiTrello,
  SiNotion,
  SiDocker,
  SiWordpress,
  SiShopify,
  SiDrupal,
} from "react-icons/si";
import { DiJava } from "react-icons/di";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  typescript: SiTypescript,
  angular: SiAngular,
  react: SiReact,
  html: SiHtml5,
  css: SiCss3,
  scss: SiSass,
  jquery: SiJquery,
  tailwind: SiTailwindcss,
  bootstrap: SiBootstrap,
  springboot: SiSpringboot,
  laravel: SiLaravel,
  php: SiPhp,
  mysql: SiMysql,
  mongodb: SiMongodb,
  postgres: SiPostgresql,
  java: DiJava,
  jira: SiJira,
  trello: SiTrello,
  notion: SiNotion,
  docker: SiDocker,
  wordpress: SiWordpress,
  shopify: SiShopify,
  drupal: SiDrupal,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
